"""empty message

Revision ID: 0b5f5a24b9c2
Revises: 74eef19b6bc9
Create Date: 2021-03-28 13:39:53.675710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5f5a24b9c2'
down_revision = '74eef19b6bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_image_path', table_name='images')
    op.create_index(op.f('ix_images_image_path'), 'images', ['image_path'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_image_path'), table_name='images')
    op.create_index('ix_images_image_path', 'images', ['image_path'], unique=False)
    # ### end Alembic commands ###
