"""empty message

Revision ID: 74eef19b6bc9
Revises: 
Create Date: 2021-03-25 23:33:57.661316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74eef19b6bc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('image_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_images_image_path'), 'images', ['image_path'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_image_path'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
